/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sendmail;

/**
 *
 * @author Minh Hoàng
 */
public class mailBody {

    public static String MAIL_BODY = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
            + "<head>\n"
            + "<!--[if gte mso 9]>\n"
            + "<xml>\n"
            + "  <o:OfficeDocumentSettings>\n"
            + "    <o:AllowPNG/>\n"
            + "    <o:PixelsPerInch>96</o:PixelsPerInch>\n"
            + "  </o:OfficeDocumentSettings>\n"
            + "</xml>\n"
            + "<![endif]-->\n"
            + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
            + "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n"
            + "  <title></title>\n"
            + "  \n"
            + "    <style type=\"text/css\">\n"
            + "      table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_6 .v-src-width { width: auto !important; } #u_content_image_6 .v-src-max-width { max-width: 30% !important; } #u_content_button_3 .v-size-width { width: 77% !important; } #u_content_button_4 .v-size-width { width: 77% !important; } }\n"
            + "@media only screen and (min-width: 670px) {\n"
            + "  .u-row {\n"
            + "    width: 650px !important;\n"
            + "  }\n"
            + "  .u-row .u-col {\n"
            + "    vertical-align: top;\n"
            + "  }\n"
            + "\n"
            + "  .u-row .u-col-100 {\n"
            + "    width: 650px !important;\n"
            + "  }\n"
            + "\n"
            + "}\n"
            + "\n"
            + "@media (max-width: 670px) {\n"
            + "  .u-row-container {\n"
            + "    max-width: 100% !important;\n"
            + "    padding-left: 0px !important;\n"
            + "    padding-right: 0px !important;\n"
            + "  }\n"
            + "  .u-row .u-col {\n"
            + "    min-width: 320px !important;\n"
            + "    max-width: 100% !important;\n"
            + "    display: block !important;\n"
            + "  }\n"
            + "  .u-row {\n"
            + "    width: calc(100% - 40px) !important;\n"
            + "  }\n"
            + "  .u-col {\n"
            + "    width: 100% !important;\n"
            + "  }\n"
            + "  .u-col > div {\n"
            + "    margin: 0 auto;\n"
            + "  }\n"
            + "}\n"
            + "body {\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "}\n"
            + "\n"
            + "table,\n"
            + "tr,\n"
            + "td {\n"
            + "  vertical-align: top;\n"
            + "  border-collapse: collapse;\n"
            + "}\n"
            + "\n"
            + "p {\n"
            + "  margin: 0;\n"
            + "}\n"
            + "\n"
            + ".ie-container table,\n"
            + ".mso-container table {\n"
            + "  table-layout: fixed;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  line-height: inherit;\n"
            + "}\n"
            + "\n"
            + "a[x-apple-data-detectors='true'] {\n"
            + "  color: inherit !important;\n"
            + "  text-decoration: none !important;\n"
            + "}\n"
            + "\n"
            + "</style>\n"
            + "  \n"
            + "  \n"
            + "\n"
            + "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><link href=\"https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
            + "\n"
            + "</head>\n"
            + "\n"
            + "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #a9f8c9;color: #000000\">\n"
            + "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\n"
            + "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\n"
            + "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #a9f8c9;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "  <tbody>\n"
            + "  <tr style=\"vertical-align: top\">\n"
            + "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #a9f8c9;\"><![endif]-->\n"
            + "    \n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table id=\"u_content_image_6\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:20px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "  <tr>\n"
            + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "      \n"
            + "      <img align=\"center\" border=\"0\" src=\"images/image-5.png\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 22%;max-width: 138.6px;\" width=\"138.6\" class=\"v-src-width v-src-max-width\"/>\n"
            + "      \n"
            + "    </td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "  <tr>\n"
            + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "      \n"
            + "      <img align=\"center\" border=\"0\" src=\"images/image-8.png\" alt=\"border\" title=\"border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 650px;\" width=\"650\" class=\"v-src-width v-src-max-width\"/>\n"
            + "      \n"
            + "    </td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f1f3f5;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #f1f3f5;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "  <tr>\n"
            + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "      \n"
            + "      <img align=\"center\" border=\"0\" src=\"images/image-6.png\" alt=\"Hero Image\" title=\"Hero Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 77%;max-width: 500.5px;\" width=\"500.5\" class=\"v-src-width v-src-max-width\"/>\n"
            + "      \n"
            + "    </td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f1f3f5;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #f1f3f5;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <h1 style=\"margin: 0px; color: #333333; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Open Sans',sans-serif; font-size: 30px;\">\n"
            + "    <strong>YOUR PRODUCT HAS DELIVERED</strong>\n"
            + "  </h1>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #5e5e5e; line-height: 170%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 170%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 16px; line-height: 27.2px;\">Sản phẩm trong đơn hàng của bạn đang được vận chuyển.</span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <h1 style=\"margin: 0px; color: #722b1d; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Open Sans',sans-serif; font-size: 25px;\">\n"
            + "    Click below to confirm the delivery!\n"
            + "  </h1>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 60px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<div align=\"center\">\n"
            + "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;\"><tr><td style=\"font-family:arial,helvetica,sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:63px; v-text-anchor:middle; width:290px;\" arcsize=\"6.5%\" stroke=\"f\" fillcolor=\"#722b1d\"><w:anchorlock/><center style=\"color:#ffffff;font-family:arial,helvetica,sans-serif;\"><![endif]-->\n"
            + "    <a href=\"http://localhost:8080/Assign_PRJ/viewCartByMail.jsp\" target=\"_blank\" class=\"v-size-width\" style=\"box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #722b1d; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:46%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #000000; border-top-style: solid; border-top-width: 0px; border-left-color: #000000; border-left-style: solid; border-left-width: 0px; border-right-color: #000000; border-right-style: solid; border-right-width: 0px; border-bottom-color: #000000; border-bottom-style: solid; border-bottom-width: 0px;\">\n"
            + "      <span style=\"display:block;padding:20px;line-height:120%;\"><span style=\"font-size: 20px; line-height: 24px; font-family: 'Open Sans', sans-serif;\">Click Here</span></span>\n"
            + "    </a>\n"
            + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
            + "</div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "  <tr>\n"
            + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "      \n"
            + "      <img align=\"center\" border=\"0\" src=\"images/image-7.png\" alt=\"border\" title=\"border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 650px;\" width=\"650\" class=\"v-src-width v-src-max-width\"/>\n"
            + "      \n"
            + "    </td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <h1 style=\"margin: 0px; color: #333333; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Open Sans',sans-serif; font-size: 40px;\">\n"
            + "    Rate our services\n"
            + "  </h1>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #722b1d; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 20px; line-height: 28px;\">★★★★★</span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #5e5e5e; line-height: 170%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 170%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 16px; line-height: 27.2px;\">Xin quý khách cho biết mức độ hài lòng với dịch vụ của chúng tôi</span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table id=\"u_content_button_3\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 70px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<div align=\"center\">\n"
            + "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;\"><tr><td style=\"font-family:arial,helvetica,sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:63px; v-text-anchor:middle; width:290px;\" arcsize=\"6.5%\" stroke=\"f\" fillcolor=\"#ea9d03\"><w:anchorlock/><center style=\"color:#ffffff;font-family:arial,helvetica,sans-serif;\"><![endif]-->\n"
            + "    <a href=\"#\" target=\"_blank\" class=\"v-size-width\" style=\"box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #ea9d03; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:46%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #000000; border-top-style: solid; border-top-width: 0px; border-left-color: #000000; border-left-style: solid; border-left-width: 0px; border-right-color: #000000; border-right-style: solid; border-right-width: 0px; border-bottom-color: #000000; border-bottom-style: solid; border-bottom-width: 0px;\">\n"
            + "      <span style=\"display:block;padding:20px;line-height:120%;\"><span style=\"font-size: 20px; line-height: 24px; font-family: 'Open Sans', sans-serif;\">Rate our services</span></span>\n"
            + "    </a>\n"
            + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
            + "</div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "  <tr>\n"
            + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "      \n"
            + "      <img align=\"center\" border=\"0\" src=\"images/image-8.png\" alt=\"border\" title=\"border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 650px;\" width=\"650\" class=\"v-src-width v-src-max-width\"/>\n"
            + "      \n"
            + "    </td>\n"
            + "  </tr>\n"
            + "</table>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f1f3f5;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #f1f3f5;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #722b1d; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-family: 'Open Sans', sans-serif; font-size: 14px; line-height: 19.6px;\"><strong><span style=\"font-size: 72px; line-height: 100.8px;\">30% </span></strong><span style=\"font-size: 72px; line-height: 100.8px;\"><span style=\"font-size: 38px; line-height: 53.2px;\">OFF</span></span></span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #787c7c; line-height: 180%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 180%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 16px; line-height: 28.8px;\">Bạn nhận được voucher giảm giá 30% cho đơn hàng tiếp theo.</span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table id=\"u_content_button_4\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 60px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<div align=\"center\">\n"
            + "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;\"><tr><td style=\"font-family:arial,helvetica,sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:63px; v-text-anchor:middle; width:290px;\" arcsize=\"6.5%\" stroke=\"f\" fillcolor=\"#722b1d\"><w:anchorlock/><center style=\"color:#ffffff;font-family:arial,helvetica,sans-serif;\"><![endif]-->\n"
            + "    <a href=\"http://localhost:8080/Assign_PRJ/HomeController\" target=\"_blank\" class=\"v-size-width\" style=\"box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #722b1d; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:46%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #000000; border-top-style: solid; border-top-width: 0px; border-left-color: #000000; border-left-style: solid; border-left-width: 0px; border-right-color: #000000; border-right-style: solid; border-right-width: 0px; border-bottom-color: #000000; border-bottom-style: solid; border-bottom-width: 0px;\">\n"
            + "      <span style=\"display:block;padding:20px;line-height:120%;\"><span style=\"font-size: 20px; line-height: 24px; font-family: 'Open Sans', sans-serif;\">Continue shopping</span></span>\n"
            + "    </a>\n"
            + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
            + "</div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #6e6e6e;\">\n"
            + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
            + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #6e6e6e;\"><![endif]-->\n"
            + "      \n"
            + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\n"
            + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\n"
            + "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\n"
            + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\n"
            + "  \n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "<div align=\"center\">\n"
            + "  <div style=\"display: table; max-width:187px;\">\n"
            + "  <!--[if (mso)|(IE)]><table width=\"187\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:187px;\"><tr><![endif]-->\n"
            + "  \n"
            + "    \n"
            + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 15px;\" valign=\"top\"><![endif]-->\n"
            + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 15px\">\n"
            + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "        <a href=\"https://linkedin.com/\" title=\"LinkedIn\" target=\"_blank\">\n"
            + "          <img src=\"images/image-2.png\" alt=\"LinkedIn\" title=\"LinkedIn\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
            + "        </a>\n"
            + "      </td></tr>\n"
            + "    </tbody></table>\n"
            + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "    \n"
            + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 15px;\" valign=\"top\"><![endif]-->\n"
            + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 15px\">\n"
            + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "        <a href=\"https://instagram.com/\" title=\"Instagram\" target=\"_blank\">\n"
            + "          <img src=\"images/image-3.png\" alt=\"Instagram\" title=\"Instagram\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
            + "        </a>\n"
            + "      </td></tr>\n"
            + "    </tbody></table>\n"
            + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "    \n"
            + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 15px;\" valign=\"top\"><![endif]-->\n"
            + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 15px\">\n"
            + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "        <a href=\"https://facebook.com/\" title=\"Facebook\" target=\"_blank\">\n"
            + "          <img src=\"images/image-1.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
            + "        </a>\n"
            + "      </td></tr>\n"
            + "    </tbody></table>\n"
            + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "    \n"
            + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 0px;\" valign=\"top\"><![endif]-->\n"
            + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 0px\">\n"
            + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "        <a href=\"https://youtube.com/\" title=\"YouTube\" target=\"_blank\">\n"
            + "          <img src=\"images/image-4.png\" alt=\"YouTube\" title=\"YouTube\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
            + "        </a>\n"
            + "      </td></tr>\n"
            + "    </tbody></table>\n"
            + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "    \n"
            + "    \n"
            + "    <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "  <tbody>\n"
            + "    <tr>\n"
            + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\n"
            + "        \n"
            + "  <div style=\"color: #ffffff; line-height: 190%; text-align: center; word-wrap: break-word;\">\n"
            + "    <p style=\"font-size: 14px; line-height: 190%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 14px; line-height: 26.6px;\"></span></p>\n"
            + "<p style=\"font-size: 14px; line-height: 190%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 14px; line-height: 26.6px;\">&copy;2022 TheNew Company |  69 đường 96 Phường 9, Quận 6, tp.HCM.</span></p>\n"
            + "  </div>\n"
            + "\n"
            + "      </td>\n"
            + "    </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "\n"
            + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
            + "  </div>\n"
            + "</div>\n"
            + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
            + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "\n"
            + "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n"
            + "    </td>\n"
            + "  </tr>\n"
            + "  </tbody>\n"
            + "  </table>\n"
            + "  <!--[if mso]></div><![endif]-->\n"
            + "  <!--[if IE]></div><![endif]-->\n"
            + "</body>\n"
            + "\n"
            + "</html>";
}
